/*
    NetVisualizer main GUI form
*/

package netvisualizer.Frontend;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import netvisualizer.NetVisualizer;

/*
 * NetVisualizer GUI base Class and Frame
 * @author Zachary Waller
 */
public class NetGui extends JFrame {

    /**
     * Creates new form NetGui
     */
    public NetGui( NetVisualizer newNetVis) {
        initComponents();
        
        netVisualizer = newNetVis;
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        setLocation
            (
                (screenSize.width / 2) - (getSize().width / 2),
                (screenSize.height / 2) - (getSize().height / 2 )
            );

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                        | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jTButton_Node = new javax.swing.JToggleButton();
        jTButton_Connection = new javax.swing.JToggleButton();
        jPanel_TooltipPanel = new javax.swing.JPanel();
        jTextPane_Tooltip = new javax.swing.JTextPane();
        jTextPane_ToolText = new javax.swing.JTextPane();
        netView = new netvisualizer.Frontend.NetView();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenu_File_Settings = new javax.swing.JMenuItem();
        jMenu_File_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetVisualizer");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("NetGui"); // NOI18N

        jToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar.setRollover(true);
        jToolBar.add(jSeparator1);

        jTButton_Node.setText("Node");
        jTButton_Node.setToolTipText("Creates a new blank Node");
        jTButton_Node.setFocusable(false);
        jTButton_Node.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTButton_Node.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTButton_Node.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTButton_NodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTButton_NodeMouseExited(evt);
            }
        });
        jTButton_Node.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTButton_NodeActionPerformed(evt);
            }
        });
        jToolBar.add(jTButton_Node);

        jTButton_Connection.setText("Connection");
        jTButton_Connection.setToolTipText("Draws a connection between two nodes");
        jTButton_Connection.setFocusable(false);
        jTButton_Connection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTButton_Connection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTButton_Connection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTButton_ConnectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTButton_ConnectionMouseExited(evt);
            }
        });
        jTButton_Connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTButton_ConnectionActionPerformed(evt);
            }
        });
        jToolBar.add(jTButton_Connection);

        jTextPane_Tooltip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane_Tooltip.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextPane_Tooltip.setEnabled(false);
        jTextPane_Tooltip.setFocusable(false);
        jTextPane_Tooltip.setOpaque(false);

        jTextPane_ToolText.setEditable(false);
        jTextPane_ToolText.setFocusable(false);
        jTextPane_ToolText.setOpaque(false);

        javax.swing.GroupLayout jPanel_TooltipPanelLayout = new javax.swing.GroupLayout(jPanel_TooltipPanel);
        jPanel_TooltipPanel.setLayout(jPanel_TooltipPanelLayout);
        jPanel_TooltipPanelLayout.setHorizontalGroup(
            jPanel_TooltipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TooltipPanelLayout.createSequentialGroup()
                .addComponent(jTextPane_Tooltip, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPane_ToolText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TooltipPanelLayout.setVerticalGroup(
            jPanel_TooltipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TooltipPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel_TooltipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextPane_ToolText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPane_Tooltip, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0))
        );

        netView.setBackground(new java.awt.Color(109, 111, 141));

        javax.swing.GroupLayout netViewLayout = new javax.swing.GroupLayout(netView);
        netView.setLayout(netViewLayout);
        netViewLayout.setHorizontalGroup(
            netViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        netViewLayout.setVerticalGroup(
            netViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jMenu_File.setText("File");

        jMenu_File_Settings.setText("Settings");
        jMenu_File_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_File_SettingsActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenu_File_Settings);

        jMenu_File_Exit.setText("Exit");
        jMenu_File_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_File_ExitActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenu_File_Exit);

        jMenuBar.add(jMenu_File);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_TooltipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_TooltipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_File_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_File_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu_File_ExitActionPerformed

    private void jTButton_NodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTButton_NodeMouseEntered
        setTooltip(jTButton_Node.getToolTipText());
    }//GEN-LAST:event_jTButton_NodeMouseEntered

    private void jTButton_NodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTButton_NodeMouseExited
        clearTooltip();
    }//GEN-LAST:event_jTButton_NodeMouseExited

    private void jTButton_ConnectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTButton_ConnectionMouseEntered
        setTooltip(jTButton_Connection.getToolTipText());
    }//GEN-LAST:event_jTButton_ConnectionMouseEntered

    private void jTButton_ConnectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTButton_ConnectionMouseExited
        clearTooltip();
    }//GEN-LAST:event_jTButton_ConnectionMouseExited

    private void jTButton_ConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTButton_ConnectionActionPerformed
        if (selectedTool == Tool.Connection)
        {
            unselectTools();
        }
        else
        {
            unselectTools();
            jTButton_Connection.setSelected(true);
            selectedTool = Tool.Connection;
            setToolText("Connection Tool");
        }
    }//GEN-LAST:event_jTButton_ConnectionActionPerformed

    private void jTButton_NodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTButton_NodeActionPerformed
        if (selectedTool == Tool.Node)
        {
            unselectTools();
        }
        else
        {
            unselectTools();
            jTButton_Node.setSelected(true);
            selectedTool = Tool.Node;
            setToolText("Node Tool");
        }
    }//GEN-LAST:event_jTButton_NodeActionPerformed

    private void jMenu_File_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_File_SettingsActionPerformed
        // Create settings manager window only if one does not already exist
        if( settingsManager == null )
        {
            settingsManager = new SettingsManager( this );
        }
        else
        {
            settingsManager.setVisible(true);
        }
    }//GEN-LAST:event_jMenu_File_SettingsActionPerformed

    
    /* My Functions */
    private void setTooltip(String text)
    {
        jTextPane_Tooltip.setText(text);
    }
    
    private void clearTooltip()
    {
        jTextPane_Tooltip.setText("");
    }
    
    private void setToolText(String text)
    {
        jTextPane_ToolText.setText(text);
    }
    
    private void unselectTools()
    {
        jTButton_Node.setSelected(false);
        jTButton_Connection.setSelected(false);
        
        selectedTool = Tool.Nothing;
        setToolText("");
    }

    /* My Variables */
    private static int numTools = 2;
    private enum Tool
    {
        Nothing, Node, Connection
    }
    
    private Tool selectedTool;
    private javax.swing.JToggleButton[] jToolButtons;
    
    public SettingsManager settingsManager = null;
    public NetVisualizer netVisualizer = null;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenuItem jMenu_File_Exit;
    private javax.swing.JMenuItem jMenu_File_Settings;
    private javax.swing.JPanel jPanel_TooltipPanel;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToggleButton jTButton_Connection;
    private javax.swing.JToggleButton jTButton_Node;
    private javax.swing.JTextPane jTextPane_ToolText;
    private javax.swing.JTextPane jTextPane_Tooltip;
    private javax.swing.JToolBar jToolBar;
    private netvisualizer.Frontend.NetView netView;
    // End of variables declaration//GEN-END:variables
}
