/*
    NetVisualizer Settings manager
*/
package netvisualizer.Frontend;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import netvisualizer.NetVisualizer;

/**
 *
 * @author Zachary Waller
 */
public class SettingsManager extends JFrame {

    /**
     * Creates new form SettingsManager
     */
    public SettingsManager( NetGui newNetGui ) {
        initComponents();
        
        netGui = newNetGui;
        netVisualizer = netGui.netVisualizer;
        
        loadVariables();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        this.setLocation
            (
                (screenSize.width / 2) - (this.getSize().width / 2),
                (screenSize.height / 2) - (this.getSize().height / 2 )
            );

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NumNodes = new javax.swing.JLabel();
        jLabel_NumSourceNodes = new javax.swing.JLabel();
        JLabel_NumDestNodes = new javax.swing.JLabel();
        JLabel_MinDegree = new javax.swing.JLabel();
        jLabel_NumPacketsToSend = new javax.swing.JLabel();
        jSpinner_NumNodes = new javax.swing.JSpinner();
        jSpinner_NumSourceNodes = new javax.swing.JSpinner();
        jSpinner_MinDegree = new javax.swing.JSpinner();
        jSpinner_NumDestNodes = new javax.swing.JSpinner();
        jSpinner_NumPacketsToSend = new javax.swing.JSpinner();
        jButton_Save = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();

        setTitle("Settings");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel_NumNodes.setText("Number of Nodes");

        jLabel_NumSourceNodes.setText("Number of Source Nodes");

        JLabel_NumDestNodes.setText("Number of Destination Nodes");

        JLabel_MinDegree.setText("Minimum Degree");

        jLabel_NumPacketsToSend.setText("Number of Packets to Send");

        jSpinner_NumNodes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_NumNodesStateChanged(evt);
            }
        });

        jSpinner_NumSourceNodes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_NumSourceNodesStateChanged(evt);
            }
        });

        jSpinner_MinDegree.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_MinDegreeStateChanged(evt);
            }
        });

        jSpinner_NumDestNodes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_NumDestNodesStateChanged(evt);
            }
        });

        jSpinner_NumPacketsToSend.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_NumPacketsToSendStateChanged(evt);
            }
        });

        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_NumNodes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner_NumNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_NumPacketsToSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner_NumPacketsToSend, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel_NumDestNodes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jSpinner_NumDestNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel_MinDegree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner_MinDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_NumSourceNodes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner_NumSourceNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NumNodes)
                    .addComponent(jSpinner_NumNodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NumSourceNodes)
                    .addComponent(jSpinner_NumSourceNodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_MinDegree)
                    .addComponent(jSpinner_MinDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_NumDestNodes)
                    .addComponent(jSpinner_NumDestNodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NumPacketsToSend)
                    .addComponent(jSpinner_NumPacketsToSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Save)
                    .addComponent(jButton_Cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner_NumNodesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_NumNodesStateChanged
        numNodes = getSpinnerValue( jSpinner_NumNodes );
    }//GEN-LAST:event_jSpinner_NumNodesStateChanged

    private void jSpinner_NumSourceNodesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_NumSourceNodesStateChanged
        numSourceNodes = getSpinnerValue( jSpinner_NumSourceNodes );
    }//GEN-LAST:event_jSpinner_NumSourceNodesStateChanged

    private void jSpinner_MinDegreeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_MinDegreeStateChanged
        minDegree = getSpinnerValue( jSpinner_MinDegree );
    }//GEN-LAST:event_jSpinner_MinDegreeStateChanged

    private void jSpinner_NumDestNodesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_NumDestNodesStateChanged
        numDestNodes = getSpinnerValue( jSpinner_NumDestNodes );
    }//GEN-LAST:event_jSpinner_NumDestNodesStateChanged

    private void jSpinner_NumPacketsToSendStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_NumPacketsToSendStateChanged
        numPacketsToSend = getSpinnerValue( jSpinner_NumPacketsToSend );
    }//GEN-LAST:event_jSpinner_NumPacketsToSendStateChanged

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        saveVariables();
        netGui.settingsManager = null;
        this.dispose();
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        netGui.settingsManager = null;
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    /* My Functions */
    // Gets spinner value if > 0
    // Sets spinner value to 0 if < 0
    private int getSpinnerValue( javax.swing.JSpinner spinner )
    {
        int value = (int) spinner.getValue();
        
        if( value < 0 )
        {
            value = 0;
            spinner.setValue( value );
        }

        return value;
    }
    
    public void loadVariables()
    {
        numNodes = netVisualizer.numNodes;
        numSourceNodes = netVisualizer.numSourceNodes;
        numDestNodes = netVisualizer.numDestNodes;
        minDegree = netVisualizer.minDegree;
        numPacketsToSend = netVisualizer.numPacketsToSend;
        
        jSpinner_NumNodes.setValue( numNodes );
        jSpinner_NumSourceNodes.setValue( numSourceNodes );
        jSpinner_NumDestNodes.setValue( numDestNodes );
        jSpinner_MinDegree.setValue( minDegree );
        jSpinner_NumPacketsToSend.setValue( numPacketsToSend );
    }
    
    public void saveVariables()
    {
        netVisualizer.numNodes = numNodes;
        netVisualizer.numSourceNodes = numSourceNodes;
        netVisualizer.numDestNodes = numDestNodes;
        netVisualizer.minDegree = minDegree;
        netVisualizer.numPacketsToSend = numPacketsToSend;
    }
    
    /* My Variables */
    public NetGui netGui = null;
    public NetVisualizer netVisualizer = null;
    
    int numNodes;
    int numSourceNodes;
    int numDestNodes;
    int minDegree;
    int numPacketsToSend;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_MinDegree;
    private javax.swing.JLabel JLabel_NumDestNodes;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel_NumNodes;
    private javax.swing.JLabel jLabel_NumPacketsToSend;
    private javax.swing.JLabel jLabel_NumSourceNodes;
    private javax.swing.JSpinner jSpinner_MinDegree;
    private javax.swing.JSpinner jSpinner_NumDestNodes;
    private javax.swing.JSpinner jSpinner_NumNodes;
    private javax.swing.JSpinner jSpinner_NumPacketsToSend;
    private javax.swing.JSpinner jSpinner_NumSourceNodes;
    // End of variables declaration//GEN-END:variables
}
